/**
* This file was automatically generated by @oraichain/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @oraichain/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import {CosmosMsgForEmpty, BankMsg, Uint128, StakingMsg, DistributionMsg, Binary, IbcMsg, Timestamp, Uint64, WasmMsg, GovMsg, VoteOption, Expiration, Coin, Empty, IbcTimeout, IbcTimeoutBlock} from "./types";
import {InstantiateMsg, ExecuteMsg, Permissions, QueryMsg, AdminListResponse, NativeBalance, AllAllowancesResponse, AllowanceInfo, AllPermissionsResponse, PermissionsInfo, Allowance, CanExecuteResponse} from "./Cw1Subkeys.types";
export interface Cw1SubkeysReadOnlyInterface {
  contractAddress: string;
  adminList: () => Promise<AdminListResponse>;
  allowance: ({
    spender
  }: {
    spender: string;
  }) => Promise<Allowance>;
  permissions: ({
    spender
  }: {
    spender: string;
  }) => Promise<PermissionsInfo>;
  canExecute: ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }) => Promise<CanExecuteResponse>;
  allAllowances: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<AllAllowancesResponse>;
  allPermissions: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<AllPermissionsResponse>;
}
export class Cw1SubkeysQueryClient implements Cw1SubkeysReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.adminList = this.adminList.bind(this);
    this.allowance = this.allowance.bind(this);
    this.permissions = this.permissions.bind(this);
    this.canExecute = this.canExecute.bind(this);
    this.allAllowances = this.allAllowances.bind(this);
    this.allPermissions = this.allPermissions.bind(this);
  }

  adminList = async (): Promise<AdminListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin_list: {}
    });
  };
  allowance = async ({
    spender
  }: {
    spender: string;
  }): Promise<Allowance> => {
    return this.client.queryContractSmart(this.contractAddress, {
      allowance: {
        spender
      }
    });
  };
  permissions = async ({
    spender
  }: {
    spender: string;
  }): Promise<PermissionsInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      permissions: {
        spender
      }
    });
  };
  canExecute = async ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }): Promise<CanExecuteResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      can_execute: {
        msg,
        sender
      }
    });
  };
  allAllowances = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<AllAllowancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_allowances: {
        limit,
        start_after: startAfter
      }
    });
  };
  allPermissions = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<AllPermissionsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_permissions: {
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface Cw1SubkeysInterface extends Cw1SubkeysReadOnlyInterface {
  contractAddress: string;
  sender: string;
  execute: ({
    msgs
  }: {
    msgs: CosmosMsgForEmpty[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  freeze: (_fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateAdmins: ({
    admins
  }: {
    admins: string[];
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  increaseAllowance: ({
    amount,
    expires,
    spender
  }: {
    amount: Coin;
    expires?: Expiration;
    spender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  decreaseAllowance: ({
    amount,
    expires,
    spender
  }: {
    amount: Coin;
    expires?: Expiration;
    spender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setPermissions: ({
    permissions,
    spender
  }: {
    permissions: Permissions;
    spender: string;
  }, _fee?: number | StdFee | "auto", _memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class Cw1SubkeysClient extends Cw1SubkeysQueryClient implements Cw1SubkeysInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.execute = this.execute.bind(this);
    this.freeze = this.freeze.bind(this);
    this.updateAdmins = this.updateAdmins.bind(this);
    this.increaseAllowance = this.increaseAllowance.bind(this);
    this.decreaseAllowance = this.decreaseAllowance.bind(this);
    this.setPermissions = this.setPermissions.bind(this);
  }

  execute = async ({
    msgs
  }: {
    msgs: CosmosMsgForEmpty[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute: {
        msgs
      }
    }, _fee, _memo, _funds);
  };
  freeze = async (_fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      freeze: {}
    }, _fee, _memo, _funds);
  };
  updateAdmins = async ({
    admins
  }: {
    admins: string[];
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_admins: {
        admins
      }
    }, _fee, _memo, _funds);
  };
  increaseAllowance = async ({
    amount,
    expires,
    spender
  }: {
    amount: Coin;
    expires?: Expiration;
    spender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      increase_allowance: {
        amount,
        expires,
        spender
      }
    }, _fee, _memo, _funds);
  };
  decreaseAllowance = async ({
    amount,
    expires,
    spender
  }: {
    amount: Coin;
    expires?: Expiration;
    spender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      decrease_allowance: {
        amount,
        expires,
        spender
      }
    }, _fee, _memo, _funds);
  };
  setPermissions = async ({
    permissions,
    spender
  }: {
    permissions: Permissions;
    spender: string;
  }, _fee: number | StdFee | "auto" = "auto", _memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_permissions: {
        permissions,
        spender
      }
    }, _fee, _memo, _funds);
  };
}